### PR TITLE
Support for adding multiple database

### PR DESCRIPTION
**Pull request by omjangir**
Please review my changes.
I have added support for adding multiple databases to read and write the purpose

### CODE REVIEW

**Comment by omjangir** [comment]
@jinzhu Can you please review changes.
I have added support to adding multiple databases to read and write purposes

**Comment by jinzhu** [comment]
I don't think it is the best solution, better to use GORM plugin system to do the job, not hacking QOR.

**Comment by omgommt** [comment]
> GORM plugin system

Thanks for the suggestion. I will check GORM plugin to solve the above use case

**Comment by omjangir** [comment]
Thanks for the suggestion. I will check GORM plugin to solve the above use case

**Comment by omjangir** [comment]
@jinzhu we could have used GORM plugin but we need the above feature only for the admin UI portal. 
If I use the gorm plugin, it will be applicable for all queries including crucial backend read APIs.
So, could you please suggest

**Comment by jinzhu** [comment]
@omjangir you could define a GORM DB instance for admin.

**Comment by omjangir** [comment]
> @omjangir you could define a GORM DB instance for admin.

Okay, This will work to define a callback for admin queries.
But more thing I am struggling with,  How can I use read DB instance in the callback function using scope reference? 
I am adding `AdminDB.Callback().Query().Register("acme:qor_read", funcToUseReadDbInstance)`

**Comment by omgommt** [comment]
> > @omjangir you could define a GORM DB instance for admin.
> > @jinzhu
> > Okay, This will work to define a callback for admin queries.
> > But more thing I am struggling with,  How can I use read DB instance in the callback function using scope reference?
> > I am adding `AdminDB.Callback().Query().Register("acme:qor_read", funcToUseReadDbInstance)`

@jinzhu Can you please update?

**Comment by bodhi** [comment]
If you want to use a separate connection than the `*gorm.Scope` that is passed to your callback, one option is to pass a closure to `Register`:

```go
var readScope *gorm.Scope // configured elsewhere

AdminDB.Callback().Query().Register("acme:qor_read", func(_ *gorm.Scope) { // parameter is ignored
  funcToUseReadDbInstance(readScope)
})
```

Note that you will run into the usual issues with consistency, such as SQL `UPDATE`s/`INSERT`s/etc in the transaction used by `AdminDB` not being visible to the read scope, because the transaction may not have `COMMIT`ed yet.

**Comment by omgommt** [comment]
> If you want to use a separate connection than the `*gorm.Scope` that is passed to your callback, one option is to pass a closure to `Register`:
> 
> ```go
> var readScope *gorm.Scope // configured elsewhere
> 
> AdminDB.Callback().Query().Register("acme:qor_read", func(_ *gorm.Scope) { // parameter is ignored
>   funcToUseReadDbInstance(readScope)
> })
> ```
> 
> Note that you will run into the usual issues with consistency, such as SQL `UPDATE`s/`INSERT`s/etc in the transaction used by `AdminDB` not being visible to the read scope, because the transaction may not have `COMMIT`ed yet.

Thanks @bodhi for suggesting
but scope contains many query related info that is different for different queries and there is no way to copy query, field, etc to new readScope (using read DB instance).
Another thing is that I need to duplicate existing queryCallback for `funcToUseReadDbInstance`

`var readScope *gorm.Scope // configured elsewhere

AdminDB.Callback().Query().Register("acme:qor_read", func(existingScope *gorm.Scope) { // parameter is ignored
  funcToCopyQueryFieldsInfoToReadScope(readScope, existingScope) // Not possible as struct contains private keys
  funcToUseReadDbInstance(readScope) // this will have duplicate the queryCallback function 
 i.e. github.com/jinzhu/gorm/callback_query.go Line no. 17
})`

**Comment by omgommt** [comment]
@jinzhu Please any update! 
last option for us to commit to our local admin repo but it will hamper future lib upgrade.
Is there any better approach you can suggest this for this feature

why the need for this feature:
There are a lot of heavy dynamic read query on DB which is affecting our booking transactional API

**Pull request closed without merging**
